version: '3.7'
services:
 php:
   build:
     context: .
     dockerfile: Dockerfile
   container_name: php-app
   ports: 
    - "80:8080" 
   links:
    - redis
 redis:
    container_name: redis
    image: redis:5
    ports:
     - "6379:6379"