version: '3.7'
services:
 php:
   build:
     context: .
     dockerfile: .
   container_name: php-app
   links:
    - redis
   volumes:
     - "./app/:/usr/src/app"
 redis:
    container_name: redis
    image: redis:5
    ports:
     - "6379:6379"